version: 2.1

defaults: &docker_img
  docker:
    - image: circleci/node:13.8.0

commands:
#   print_pipeline_id:
#     description: "print pipeline id"
#     parameters:
#       to:
#         type: string
#         default: $CIRCLE_WORKFLOW_ID
#     steps:
#       - run: echo << parameters.to >>


# jobs:
#   say-hello:
#     docker:
#       - image: cimg/base:stable
#     steps:
#       - checkout
#       - run:
#           name: "Say hello"
#           command: echo $HELLO

#   list-files:
#     docker:
#       - image: cimg/base:stable

#     steps:
#       - checkout
#       - run:
#           name: "List Files"
#           command: "ls -al"

#   save-hello-to-file:
#     docker:
#       - image: cimg/base:stable

#     steps:
#       - run:
#           name: "Save Hello"
#           command: echo $HELLO > ~/output.txt 

#       - persist_to_workspace:
#           root: ~/
#           paths:
#             - output.txt

#   get-data-from-persist:
#     docker:
#       - image: cimg/base:stable

#     steps:
#       - attach_workspace:
#           at: ~/
#       - run:
#           command: cat ~/output.txt

  # print_pipeline_id:
  #   <<: *docker_img
  #   steps:
  #     - print_pipeline_id

  make_failure_job:
    <<: *docker_img
    steps:
      run: echo $non_existing_var

  job_to_run_on_failure:
    <<: *docker_img
    steps:
      run: echo "Hello Failure"
      when: on_fail

workflows:
  say-hello-workflow:
    jobs:

  #     - say-hello
  #     - list-files:
  #         requires:
  #           - say-hello
  #     - save-hello-to-file
  #     - get-data-from-persist:
  #         requires:
  #           - save-hello-to-file
        # - print_pipeline_id
      - make_failure_job
      - job_to_run_on_failure
